### ISSUE TITLE
Making code error free and remove unneccesary code

### ISSUE THREAD

**Issue by Berehum** [TinyYana/SlimeChunkChecker#1]
Hi, I saw your plugin on Spigot and decided to check out the source code. I've seen some things that will cause errors, or are unneccessary. This is purely to help you out, and it's your choice if you're going to implement these changes.

## First of all: 
https://github.com/TinyYana/SlimeChunkChecker/blob/ae91e6d05d4fc12ec80a0844c583296718c7220b/src/main/java/io/github/tinyyana/slimechunkchecker/SlimeChunkCheckCommand.java#L30
This if clause is quite unneccesary because you already have an else clause.

## Second of all:
https://github.com/TinyYana/SlimeChunkChecker/blob/ae91e6d05d4fc12ec80a0844c583296718c7220b/src/main/java/io/github/tinyyana/slimechunkchecker/SlimeChunkCheckCommand.java#L21
Having unchecked player casts might cause errors whenever the command is executed by console.
I would personally implement this code which checks if a sender is a player:
```java
if (!(sender instanceof Player)) {
  sender.sendMessage(ChatColor.RED + "You must be a player to execute this command!")
  return true;
}
```
You could of course make that message customizable.

## Third of all:
https://github.com/TinyYana/SlimeChunkChecker/blob/ae91e6d05d4fc12ec80a0844c583296718c7220b/src/main/java/io/github/tinyyana/slimechunkchecker/SlimeChunkCheckCommand.java#L36
I would personally not return false here. Returning false means that whenever the command has an usage, it will display it to the sender.

If you have any questions, don't hesitate to ask them!
Have a good day! :D

**Comment by TinyYana** [comment]
Hello, what you suggested has been released in version 1.3, thank you very much for your suggestions.
